### ISSUE TITLE
Uncaught (in promise) 500 on live demo page

### ISSUE THREAD

**Issue by camiblanch** [googlecreativelab/aiexperiments-ai-duet#11]
After I play a tune the AI doesn't play back to me. Instead I get 
`POST https://aiexperiments.withgoogle.com/ai-duet/view/predict?duration=3.1346938775510207 500 ()
(anonymous) @ 0.js:21
value @ 0.js:21
(anonymous) @ 0.js:18
value @ 0.js:18`
and
`Uncaught (in promise) 500` as console errors. 
This is seen on the [live demo page](https://aiexperiments.withgoogle.com/ai-duet/view/)

**Comment by camiblanch** [comment]
Issue just went away. Never mind 😛

**Comment by camiblanch** [comment]
I realized that the issue is that there is high traffic on the page currently as it was just released live. No real problems to see

**Comment by tambien** [comment]
Thanks for letting us know! we got a lot of traffic all of a sudden and it took the load balancer a minute to scale up to accommodate.
