### ISSUE TITLE
"GET /build/Main.js HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by neiljelmert** [googlecreativelab/aiexperiments-ai-duet#12]
Installed the python way, and got the `404` error on the `Main.js`. Then installed the docker way, and the same thing occurred. I have `Node.js version 7.6.0 current`, and `webpack 2.x`. Running in a virtual environment with the repo cloned at my root.

Sometimes I get: 

```
127.0.0.1 - - [24/Feb/2017 19:31:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2017 19:31:46] "GET /build/Main.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Feb/2017 19:31:47] "GET /build/Main.js HTTP/1.1" 404 -
127.0.0.1 - - [24/Feb/2017 19:31:47] "GET /images/AIDuet_196.png HTTP/1.1" 304 -
127.0.0.1 - - [24/Feb/2017 19:31:47] "GET /images/AIDuet_152.png HTTP/1.1" 304 -
127.0.0.1 - - [24/Feb/2017 19:31:47] "GET /images/AIDuet_32.png HTTP/1.1" 304 -
```

in one setting.

The site remains white and empty throughout. Any ideas? Forgive me, I'm a newb when it comes to installation management.

**Comment by tambien** [comment]
It seems like maybe you didn't build the project. Follow the instructions at the bottom of the [installation instructions section](https://github.com/googlecreativelab/aiexperiments-ai-duet#installation) to build the static files: 

```
cd static
npm install
webpack -p
```

Are you getting an error at this part?

**Comment by neiljelmert** [comment]
Nope, the error is when I go to the website, and my terminal is automatically filled by those 404 error, etc. When I ran the instructions you just posted, I get

```
npm install webpack -p
/Users/neiljelmert/aiexperiments-ai-duet/static/node_modules/webpack
npm WARN ai-duet@1.0.0 No description
npm WARN ai-duet@1.0.0 No license field.
```

**Comment by tambien** [comment]
make sure you're first running `npm install`, then hit enter, and then run `webpack -p`. From your snippet, it looks like you've got it all on one line.

**Comment by neiljelmert** [comment]
After `npm install` I get 

```
npm WARN ai-duet@1.0.0 No description
npm WARN ai-duet@1.0.0 No license field.
```

After `webpack -p` I now get

`-bash: webpack: command not found`

Sorry for the hassle!

**Comment by tambien** [comment]
Strange, it seems like you might have an older version of the code. There is no 'app/Main' that's been renamed to 'src/Main'. Make sure you pull the latest code from github.

**Comment by neiljelmert** [comment]
Alright, I did a clean pull/install and had no issues with webpack, etc. Also, I see `'Main': 'src/Features'` in the `webpack.config.js`, so no more `app/Main` issue. Now I have this issue:

```
/server$ python server.py 
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Feb/2017 20:43:20] "GET / HTTP/1.1" 200 -
```

which seems like it should be working, but going to the browser (Chrome) yields a blank white page.

**Comment by neiljelmert** [comment]
Issue solved by using Safari. Thanks for the help! =]

**Comment by piteight** [comment]
I find this issue helpfull, but its not visible from github issue page. I had to find it via neiljelmert activity... strange.

**Comment by piyush320** [comment]
I also find the same issue . And still have no solution for that .
