### ISSUE TITLE
Is there a way I can use acoustic audio input?

### ISSUE THREAD

**Issue by billchenxi** [googlecreativelab/aiexperiments-ai-duet#16]
Is there a way I can use acoustic audio input? How can I do it? What kind of library I need to use?
Thanks!

**Comment by tambien** [comment]
Not easily. You'd need to be able to turn your acoustic input into MIDI data before it can be fed into AI Duet. I think there are a few tools that do this, though i don't know any off the top of my head and i'm not sure how accurate they are.
