### ISSUE TITLE
Getting Uncaught typerror

### ISSUE THREAD

**Issue by Naim08** [googlecreativelab/aiexperiments-ai-duet#19]
Hey,

After I have the server up, whenever I click on a key, I get the error below(on the picture). I tried both the basic and docker setup on multiple other computers(Mac, Ubuntu) and they yielded the same result. I should mention that after the error is prompted, the AI does not play. Any help would be greatly appreciated. Thank you.
<img width="1612" alt="screen shot 2017-11-15 at 12 20 39 pm" src="https://user-images.githubusercontent.com/6713445/32850539-769c34fa-ca00-11e7-9699-7e0e95d7b489.png">

.

**Comment by tambien** [comment]
i think this is fixed with the latest push. try a clean reinstall
