### ISSUE TITLE
Python 2 isn't supported by TensorFlow

### ISSUE THREAD

**Issue by donno2048** [googlecreativelab/aiexperiments-ai-duet#34]
In the README this is written:
> A.I. Duet only works with Python 2.7

but in the TensorFlow installing site:
> Requires Python 3.5–3.8

so how can I use it?

If I use the TensorFlow version specified in the README pip can't find this version and if I try to use a newer version or install from the whl from storage.googleapis.com(/tensorflow/...) it says my version is not supported

**Comment by donno2048** [comment]
I tried to just install the latest version of each module using Python 3 and got this error:
```py
ModuleNotFoundError: No module named 'magenta.protobuf'
```
is it replaceable?

**Comment by yty** [comment]
> 我尝试使用 Python 3 安装每个模块的最新版本，但收到此错误：
> 
> ModuleNotFoundError: No module named 'magenta.protobuf'
> 它是可更换的吗？

"Did you eventually manage to install it successfully?"

**Comment by donno2048** [comment]
> > 我尝试使用 Python 3 安装每个模块的最新版本，但收到此错误：
> > 
> > ModuleNotFoundError: No module named 'magenta.protobuf'
> > 它是可更换的吗？
> 
> "Did you eventually manage to install it successfully?"

Couldn't tell ya, 5 years was a very long time ago
