### ISSUE TITLE
`Could not find a version that satisfies the requirement magenta==0.1.3`

### ISSUE THREAD

**Issue by gnestor** [googlecreativelab/aiexperiments-ai-duet#4]
`pip install -r requirements.txt` results in:

```
Collecting magenta==0.1.3 (from -r requirements.txt (line 15))
  Could not find a version that satisfies the requirement magenta==0.1.3 (from -r requirements.txt (line 15)) (from versions: )
No matching distribution found for magenta==0.1.3 (from -r requirements.txt (line 15))
```

According to the [magenta install instructions](https://github.com/tensorflow/magenta#automated-install), more than a `pip install magenta` is required (e.g. create conda source environment, install TensorFlow in that environment, etc.). After I followed the "automated install" instructions and activated the magenta source environment, I ran `pip install -r requirements.txt` and everything installed without error.

Am I missing something or should the README be updated?

**Comment by tambien** [comment]
ok good catch. I'll make a note in the README to link to the Magenta installation instructions and take it out of the requirements.txt file.
