### ISSUE TITLE
Getting some help with setup

### ISSUE THREAD

**Issue by skymasterson** [googlecreativelab/aiexperiments-ai-duet#7]
After installing all the package, I'm getting the following error after starting the server with "python server.py"

Any tips on what I might have missed?

  File "/Users/XXX/projects/aiexperiments-ai-duet/server/predict.py", line 19, in <module>
    import third_party.magenta.models.basic_rnn.basic_rnn_generator as basic_rnn_generator
  File "/Users/XXX/projects/aiexperiments-ai-duet/server/third_party/magenta/models/basic_rnn/basic_rnn_generator.py", line 17, in <module>
    import basic_rnn_encoder_decoder
  File "/Users/XXX/projects/aiexperiments-ai-duet/server/third_party/magenta/models/basic_rnn/basic_rnn_encoder_decoder.py", line 27, in <module>
    class MelodyEncoderDecoder(melodies_lib.MelodyEncoderDecoder):
AttributeError: 'module' object has no attribute 'MelodyEncoderDecoder'

**Comment by VadimDez** [comment]
Got same here

**Comment by zizau** [comment]
Me too

**Comment by fabianhemmert** [comment]
...same here! (Python 2.7.12, OSX)

**Comment by Domojz** [comment]
same for me. python 2.7.12, OSX 10.9.5

**Comment by python273** [comment]
You can try to use my branch https://github.com/python273/aiexperiments-ai-duet/tree/add_dockerfile or just run it in Docker. Dockerfile is in my branch too.

**Comment by nickplee** [comment]
@python273 you da man.

**Comment by ilukasschneider** [comment]
@python273 after doing all your steps: 

AttributeError: 'module' object has no attribute 'MelodyEncoderDecoder'


So what now?

**Comment by python273** [comment]
@ilukasschneider have you run docker container? Or?

**Comment by ilukasschneider** [comment]
@python273 yes i did this docker thingy you had on your branch..! (sry for my newbiness)

I am now deleting all the stuff and trying to do it again!

**Comment by tambien** [comment]
Merged Docker branch. Using Docker should simplify / normalize installation. 

I will close this for now.
