### ISSUE TITLE
Syntax Error  print time.time() - now

### ISSUE THREAD

**Issue by yewzy** [googlecreativelab/aiexperiments-ai-duet#8]
After installing all the packages, I can't run the server. This is the error I got.
  File "server.py", line 40
    print time.time() - now
             ^
SyntaxError: invalid syntax

Did I do anything wrong?

**Comment by tambien** [comment]
Looks like you're using python3 print method. and i'm pretty sure that Magenta only runs in python 2.7, so try checking your python version before running. I will also make a note in the README.

But either way, those lines were just in there for debugging, you can go ahead and delete them.
